# Generated by Django 5.2.13 on 2026-04-11 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='buffer_minutes',
            field=models.IntegerField(default=5, help_text='Buffer time between sessions in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='session_duration_minutes',
            field=models.IntegerField(help_text='Duration of each session in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
